### ISSUE TITLE
从 鬼斩的Maven构建站中下载的版本#30不能正常加载

### ISSUE THREAD

**Issue by CTimet** [SlimefunGuguProject/DynaTech#27]
## 描述：
我想给服务器加上动力科技插件，于是去bing了一下，找到了以下帖子：https://www.mcbbs.net/thread-1299240-1-1.html
于是我跟着帖子的指引来到了鬼斩的Maven构建站，最初，我下载了#31的版本，可是不能正常加载，我又去下#30的版本，也不能正常加载，于是我便在这里发一个issues

## 重现问题：
一个普通的服务器，开启后加载动力科技#30构建版本时报错

## 预期行为：
我希望能够正常加载动力科技

## 服务器日志：
https://pastebin.com/9YGT5i6R

## 运行时环境：
1.Java：jdk-17.0.2
2.Server Version：paper-1.18.2-333
3.Minecraft Version : 1.18.2
4.Slimefun Version : Slimefun v2022.04-release (中文汉化版)
5.Other plugins : 
![image](https://user-images.githubusercontent.com/92621765/169680720-c404c644-56b9-444e-91da-8ea0e95f8be9.png)
![image](https://user-images.githubusercontent.com/92621765/169680721-d67d18a9-fd91-42db-ae61-97f4aab6357a.png)
6.Other : 该服务器使用了由Youmiel提供的浮岛数据包，该数据包下载地址https://github.com/Youmiel/FloatingIslands-Datapack
介绍：https://www.bilibili.com/video/BV1kS4y1b79R?bbid=XYBAC85B3190C8C5FAE39563828CD56FB17F7&ts=1653038586742

**Comment by ybw0014** [comment]
你这是官方版的

**Comment by ybw0014** [comment]
而且官方版也落后了好多版本

**Comment by CTimetbukii** [comment]
那应该从哪里下载合适的版本？

**Comment by ybw0014** [comment]
https://builds.guizhanss.net/ybw0014/DynaTech/master

**Comment by CTimetbukii** [comment]
这不巧了吗，我就是从这里下的
我最开始就是从这里下的#31版本，然后报错，然后去下的#30版本，然后接着报错，我上面都说了从鬼斩的Maven构建站中下的，上面的堆栈就是从构建站中下的#30版本的报错

**Comment by ybw0014** [comment]
但是，你这报错是官方版的报错，所以请尝试重新下载

**Comment by CTimetbukii** [comment]
好吧，那我录制个视频，给你看看我是怎么从你这里下载然后接着发生报错的

**Comment by CTimetbukii** [comment]
抱歉抱歉实在是抱歉，录视频的时候看了一下，确实是官方版的，主要是我在配置服务器的时候，忘了删除官方版的了 ，导致汉化版和官方版冲突报错，然后我就认为汉化版有错，结果投了官方版的堆栈，实在是抱歉，是我不仔细，构建版本没有错，给您添麻烦了。抱歉
