### ISSUE TITLE
便携式液体储存罐可以在下界放水

### ISSUE THREAD

**Issue by HowieHz** [SlimefunGuguProject/DynaTech#32]
## Description (Required)
便携式液体储存罐可以在下界放水

## Steps to reproduce the Issue (Required)
![image](https://user-images.githubusercontent.com/94725606/183822346-311914cb-8529-4fbf-9cba-479cf5b2fcf9.png)

![image](https://user-images.githubusercontent.com/94725606/183822367-4fcb5a6c-4d3b-44b7-a4c6-b53688ae72d7.png)

 - Minecraft Version:purpur1.19.1
 - CS-CoreLib Version:无
 - Slimefun Version:2022.07-release
 - Plugin Version: 33

**Comment by ybw0014** [comment]
e86a9b1
