### ISSUE TITLE
111

### ISSUE THREAD

**Issue by hed516** [SlimefunGuguProject/DynaTech#51]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/DynaTech/issues)，且没有找到相同的问题

### 问题描述

警告 MobDataCard - 'VEX_DATA_CARD' (DynaTech vBuild 45 zh-CN(ybw0014) (git 71dc547)): This item does not belong into ItemGroup SubGroup {infinityexpansion:mob_simulation,tier=3} as that group belongs to InfinityExpansion
01.03 16:46:33 [服务器] 警告 You can report this warning here: https://github.com/SlimefunGuguProject/DynaTech/issues
01.03 16:46:33 [服务器] 警告 MobDataCard - 'PHANTOM_DATA_CARD' (DynaTech vBuild 45 zh-CN(ybw0014) (git 71dc547)): This item does not belong into ItemGroup SubGroup {infinityexpansion:mob_simulation,tier=3} as that group belongs to InfinityExpansion
01.03 16:46:33 [服务器] 警告 You can report this warning here: https://github.com/SlimefunGuguProject/DynaTech/issues

### 复现步骤

警告 MobDataCard - 'VEX_DATA_CARD' (DynaTech vBuild 45 zh-CN(ybw0014) (git 71dc547)): This item does not belong into ItemGroup SubGroup {infinityexpansion:mob_simulation,tier=3} as that group belongs to InfinityExpansion
01.03 16:46:33 [服务器] 警告 You can report this warning here: https://github.com/SlimefunGuguProject/DynaTech/issues
01.03 16:46:33 [服务器] 警告 MobDataCard - 'PHANTOM_DATA_CARD' (DynaTech vBuild 45 zh-CN(ybw0014) (git 71dc547)): This item does not belong into ItemGroup SubGroup {infinityexpansion:mob_simulation,tier=3} as that group belongs to InfinityExpansion
01.03 16:46:33 [服务器] 警告 You can report this warning here: https://github.com/SlimefunGuguProject/DynaTech/issues

### 预期行为

警告 MobDataCard - 'VEX_DATA_CARD' (DynaTech vBuild 45 zh-CN(ybw0014) (git 71dc547)): This item does not belong into ItemGroup SubGroup {infinityexpansion:mob_simulation,tier=3} as that group belongs to InfinityExpansion
01.03 16:46:33 [服务器] 警告 You can report this warning here: https://github.com/SlimefunGuguProject/DynaTech/issues
01.03 16:46:33 [服务器] 警告 MobDataCard - 'PHANTOM_DATA_CARD' (DynaTech vBuild 45 zh-CN(ybw0014) (git 71dc547)): This item does not belong into ItemGroup SubGroup {infinityexpansion:mob_simulation,tier=3} as that group belongs to InfinityExpansion
01.03 16:46:33 [服务器] 警告 You can report this warning here: https://github.com/SlimefunGuguProject/DynaTech/issues

### 服务端软件

Spigot

### Minecraft版本

1.19.3

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

v4.9

### 插件版本

45

**Comment by ybw0014** [comment]
已知问题，不影响使用
