### ISSUE TITLE
物品栏过滤器不能正常生效

### ISSUE THREAD

**Issue by Violet-Nonbloosom** [SlimefunGuguProject/DynaTech#64]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/DynaTech/issues)，且没有找到相同的问题

### 问题描述

根据 `InventoryFilterListener.java` 的代码，汉化版物品栏过滤器的原理为：只要存在一格物品与掉落物**不匹配**，就将掉落物加入物品栏。

这意味着过滤器**必须全放同种物品**才能正常生效。

这与原版效果不一致。

可以断定这个漏洞与汉化版 `BlockStorage` **无关**，也与背包命名、物品堆叠数目**无关**。

### 复现步骤

1. 合成一个新的物品栏过滤器，并对其命名。
2. 向过滤器第一格放置一个末地石，第二格放置一个末地石砖。
3. 尝试拾取一个末地石掉落物。
4. 拾取成功。
5. 对末地石砖重复上述步骤 3,4，同样拾取成功。
6. 移除过滤器的末地石砖，然后尝试拾取一个末地石掉落物。
7. 拾取成功。

### 预期行为

过滤器中**只要存在一格**物品与掉落物匹配，就放弃将掉落物加入物品栏。
复现步骤中的每次尝试拾取均**失败**。

### 服务端软件

Spigot

### Minecraft 版本

1.19.2

### Slimefun版本

![图片](https://github.com/SlimefunGuguProject/DynaTech/assets/86547296/86813f12-1157-4d41-a7d9-c3173207e6ea)

### 插件版本

Build 58 (git 7707d44)

**Comment by ybw0014** [comment]
正好在合并上游，在修了

**Comment by ybw0014** [comment]
临时禁用了，修的时候遇到了点奇怪的问题，等修好恢复

**Comment by ybw0014** [comment]
已修复
